version: "3.8"

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MojSifra123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql  # Za spremanje podataka između restartova
    networks:
      - template_network

networks:
  template_network:
    driver: bridge

volumes:
  mssql_data:
    driver: local
