// <auto-generated />
using System;
using ImenikApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImenikApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250317055931_databaseSchema")]
    partial class databaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImenikApp.Models.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Drzava", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Hrvatska"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Srbija"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Spanija"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Njemacka"
                        });
                });

            modelBuilder.Entity("ImenikApp.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Grad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DrzavaId = 1,
                            Naziv = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            DrzavaId = 1,
                            Naziv = "Tuzla"
                        },
                        new
                        {
                            Id = 3,
                            DrzavaId = 1,
                            Naziv = "Banja Luka"
                        },
                        new
                        {
                            Id = 4,
                            DrzavaId = 1,
                            Naziv = "Mostar"
                        },
                        new
                        {
                            Id = 5,
                            DrzavaId = 1,
                            Naziv = "Sarajevo"
                        },
                        new
                        {
                            Id = 6,
                            DrzavaId = 2,
                            Naziv = "Zagreb"
                        },
                        new
                        {
                            Id = 7,
                            DrzavaId = 2,
                            Naziv = "Split"
                        },
                        new
                        {
                            Id = 8,
                            DrzavaId = 2,
                            Naziv = "Rijeka"
                        },
                        new
                        {
                            Id = 9,
                            DrzavaId = 3,
                            Naziv = "Beograd"
                        },
                        new
                        {
                            Id = 10,
                            DrzavaId = 3,
                            Naziv = "Nis"
                        },
                        new
                        {
                            Id = 11,
                            DrzavaId = 3,
                            Naziv = "Novi Sad"
                        },
                        new
                        {
                            Id = 12,
                            DrzavaId = 4,
                            Naziv = "Madrid"
                        },
                        new
                        {
                            Id = 13,
                            DrzavaId = 4,
                            Naziv = "Barcelona"
                        },
                        new
                        {
                            Id = 14,
                            DrzavaId = 5,
                            Naziv = "Minhen"
                        },
                        new
                        {
                            Id = 15,
                            DrzavaId = 5,
                            Naziv = "Berlin"
                        },
                        new
                        {
                            Id = 16,
                            DrzavaId = 5,
                            Naziv = "Frankfurt"
                        });
                });

            modelBuilder.Entity("ImenikApp.Models.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pol")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId");

                    b.HasIndex("GradId");

                    b.ToTable("Osobe");
                });

            modelBuilder.Entity("ImenikApp.Models.Grad", b =>
                {
                    b.HasOne("ImenikApp.Models.Drzava", "Drzava")
                        .WithMany("Gradovi")
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("ImenikApp.Models.Osoba", b =>
                {
                    b.HasOne("ImenikApp.Models.Drzava", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImenikApp.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzava");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("ImenikApp.Models.Drzava", b =>
                {
                    b.Navigation("Gradovi");
                });
#pragma warning restore 612, 618
        }
    }
}
